const guests = [
  {
    id: "cpp001",
    name: "William",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "cpp002",
    name: "Roby Pontri Pratama",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "cpp003",
    name: "Jonathan Maulana",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "cpp004",
    name: "Deva Andre Johano",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "cpp005",
    name: "Fahmi Nur Ismail",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "cpp006",
    name: "Kelvin Robeto",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "cpp007",
    name: "David Parlindungan",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "cpp008",
    name: "Rizki Anandar Saputra",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "cpp009",
    name: "Rifai Millah",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "cpp010",
    name: "Fulki FIrdaus",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "cpp011",
    name: "Ahmad Pahlefi",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "cpp012",
    name: "Irfan Ardian",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "cpp013",
    name: "Wibi Aulianto",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "cpp014",
    name: "Ezhar",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "cpp015",
    name: "Ustadz Sholehudin",
    family: "Groom",
    association: "Masjid Khidmatus Sunnah",
  },
  {
    id: "cpp016",
    name: "Fernando Hilyadi MKS",
    family: "Groom",
    association: "Masjid Khidmatus Sunnah",
  },
  {
    id: "cpp017",
    name: "Asep Saepullah MKS",
    family: "Groom",
    association: "Masjid Khidmatus Sunnah",
  },
  {
    id: "cpp018",
    name: "Arif MKS",
    family: "Groom",
    association: "Masjid Khidmatus Sunnah",
  },
  {
    id: "cpp019",
    name: "Heri MKS",
    family: "Groom",
    association: "Masjid Khidmatus Sunnah",
  },
  {
    id: "cpp020",
    name: "Ustadz Purwanto",
    family: "Groom",
    association: "Guru Tahsin",
  },
  {
    id: "cpp021",
    name: "Agami PDAM",
    family: "Groom",
    association: "Teman PDAM",
  },
  {
    id: "cpp022",
    name: "Ahmad Faisal PDAM",
    family: "Groom",
    association: "Teman PDAM",
  },
  {
    id: "cpp023",
    name: "Hafiz PDAM",
    family: "Groom",
    association: "Teman PDAM",
  },
  {
    id: "cpp024",
    name: "Ridwan PDAM",
    family: "Groom",
    association: "Teman PDAM",
  },
  {
    id: "cpp025",
    name: "Komunitas Masjid Khidmatus Sunnah",
    family: "Groom",
    association: "Masjid Khidmatus Sunnah",
  },
  {
    id: "cpp026",
    name: "Santri / Muta'allim Kajian Intensif MKS",
    family: "Groom",
    association: "",
  },
  {
    id: "cpp027",
    name: "Pengabdian El Azzam La Tansa",
    family: "Groom",
    association: "",
  },
  {
    id: "cpp028",
    name: "Keluarga Besar H. Sukra",
    family: "Groom",
    association: "",
  },
  {
    id: "cpp029",
    name: "Keluarga Besar H. Sukra",
    family: "Groom",
    association: "",
  },
  {
    id: "cpp030",
    name: "Keluarga Besar Hj Gancang",
    family: "Groom",
    association: "",
  },
  {
    id: "cpp031",
    name: "Keluarga Besar H. Syukriyah",
    family: "Groom",
    association: "",
  },
  {
    id: "cpp032",
    name: "Grup Bapak Bapak Rasis",
    family: "Groom",
    association: "",
  },
  {
    id: "cpw001",
    name: "Keluarga Besar Achmad Roedja'i",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw002",
    name: "Keluarga Besar Hikmat Setiawan",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw003",
    name: "Yayasan Pendidikan Islam Imam Ahmad bin Hanbal (SDIT Anak Shalih)",
    family: "Bride",
    association: "SDIT Anak Shalih",
  },
  {
    id: "cpw004",
    name: "Yayasan Pendidikan Islam Imam Ahmad bin Hanbal (TKIT Aisyah Educare)",
    family: "Bride",
    association: "TKIT Aisyah Educare",
  },
  {
    id: "cpw005",
    name: "Bulan Bintang Islamic School",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw006",
    name: "Mu'allimat Rattil Ayatihi",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw007",
    name: "Mu'allimaat Daarunnisaa",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw008",
    name: "Mu'allimaat Nurul Ilmi Lil Athfal",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw009",
    name: "Rumah Cinta Quran",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw010",
    name: "Thalibaat Tahsin Shahabah Mengaji",
    family: "Bride",
    association: "Murid-murid tahsin",
  },
  {
    id: "cpw011",
    name: "Tim Janaiz Akhawat Masjid Nurul Iman Blok M Square",
    family: "Bride",
    association: "Tim yang membantu administrasi tahsin di Masjid Nurul Iman.",
  },
  {
    id: "cpw012",
    name: "Student Committee Sisters IOU Indonesia",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw013",
    name: "Ambarita Mumpuni",
    family: "Bride",
    association: "Teman SMP",
  },
  {
    id: "cpw014",
    name: "Meiliana Indri Sagita",
    family: "Bride",
    association: "Teman SMP",
  },
  {
    id: "cpw015",
    name: "Dini Hanifah",
    family: "Bride",
    association: "Teman Ma'had dan kuliah.",
  },
  {
    id: "cpw016",
    name: "Kinta Nilaya Aprira",
    family: "Bride",
    association: "Teman SMP. .",
  },
  {
    id: "cpw017",
    name: "Megawati",
    family: "Bride",
    association: "Teman SMP.",
  },
  {
    id: "cpw018",
    name: "Teh Virna Nur'afianty Dewi",
    family: "Bride",
    association: "Teman kajian di Bandung.",
  },
  {
    id: "cpw019",
    name: "Teh Shofiyah Asmanadyah",
    family: "Bride",
    association: "Teman kajian di Bandung.",
  },
  {
    id: "cpw020",
    name: "Rizqiah",
    family: "Bride",
    association: "Teman kajian di Bandung.",
  },
  {
    id: "cpw021",
    name: "Yasfika Ely Nur Afifah",
    family: "Bride",
    association: "Teman Ma'had dan kuliah.",
  },
  {
    id: "cpw022",
    name: "Erika Khairunnisa",
    family: "Bride",
    association: "Teman Ma'had dan kuliah.",
  },
  {
    id: "cpw023",
    name: "Rizka Amelia",
    family: "Bride",
    association: "Teman Ma'had dan kuliah.",
  },
  {
    id: "cpw024",
    name: "Teh Asy-Syifa Rizqiawati Casmat",
    family: "Bride",
    association: "Kemungkinan hadir dengan suami.",
  },
  {
    id: "cpw025",
    name: "Ummu Santy Purnamasari",
    family: "Bride",
    association: "Murid tahsin privat",
  },
  {
    id: "cpw026",
    name: "Ummu dr. Desvita Rosana, Sp.An",
    family: "Bride",
    association: "Murid tahsin privat",
  },
  {
    id: "cpw027",
    name: "Ummu Tuti Alawiyah",
    family: "Bride",
    association: "Murid tahsin privat",
  },
  {
    id: "cpw028",
    name: "Bu Enalita",
    family: "Bride",
    association: "Murid tahsin privat",
  },
  {
    id: "cpw029",
    name: "Aida Rahmah Nuralimah",
    family: "Bride",
    association: "Kemungkinan hadir dengan suami.",
  },
  {
    id: "cpw030",
    name: "Nopiya",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw031",
    name: "Bu Tia Ummu Manda",
    family: "Bride",
    association: "Orang tua murid tahfidz privat.",
  },
  {
    id: "cpw032",
    name: "Bunda Ratih Ummu Fatih",
    family: "Bride",
    association: "Orang tua murid privat",
  },
  {
    id: "cpw033",
    name: "Bunda Damar Ummu Abyaz",
    family: "Bride",
    association: "Murid tahsin privat",
  },
  {
    id: "cpw034",
    name: "Bunda Meita Ummu Ammar",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw035",
    name: "Bunda Farah Ummu Hamzah",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw036",
    name: "Shalihaat 6C dan 6D Angkatan 11",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw037",
    name: "Ustadzah Pipit Aprilianti",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw038",
    name: "Ustadzah Santi Kamelia",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw039",
    name: "Teh Tia Ridotiani",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw040",
    name: "Teh Triyani Indah Lestari",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw041",
    name: "Dewi Ais Solawati",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw042",
    name: "Kak Bilqisthi",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw043",
    name: "Bunda Selviah",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw044",
    name: "Bunda Silvi",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw045",
    name: "Bunda Nia",
    family: "Bride",
    association: "",
  },
  {
    id: "cpw046",
    name: "Shalimar",
    family: "Bride",
    association: "",
  },
];
