const guests = [
  {
    id: "CPP001",
    name: "William",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "CPP002",
    name: "Roby Pontri Pratama",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "CPP003",
    name: "Jonathan Maulana",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "CPP004",
    name: "Deva Andre Johano",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "CPP005",
    name: "Fahmi Nur Ismail",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "CPP006",
    name: "Kelvin Robeto",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "CPP007",
    name: "David Parlindungan",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "CPP008",
    name: "Rizki Anandar Saputra",
    family: "Groom",
    association: "Teman Binus",
  },
  {
    id: "CPP009",
    name: "Rifai Millah",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "CPP010",
    name: "Fulki FIrdaus",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "CPP011",
    name: "Ahmad Pahlefi",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "CPP012",
    name: "Irfan Ardian",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "CPP013",
    name: "Wibi Aulianto",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "CPP014",
    name: "Ezhar",
    family: "Groom",
    association: "Teman La tansa",
  },
  {
    id: "CPP015",
    name: "Ustadz Sholehudin",
    family: "Groom",
    association: "Masjid Khidmatus Sunnah",
  },
  {
    id: "CPP016",
    name: "Fernando Hilyadi",
    family: "Groom",
    association: "Masjid Khidmatus Sunnah",
  },
  {
    id: "CPP017",
    name: "Asep Saepudin",
    family: "Groom",
    association: "Masjid Khidmatus Sunnah",
  },
  {
    id: "CPP018",
    name: "Arif",
    family: "Groom",
    association: "Masjid Khidmatus Sunnah",
  },
  {
    id: "CPP019",
    name: "Heri",
    family: "Groom",
    association: "Masjid Khidmatus Sunnah",
  },
  {
    id: "CPP020",
    name: "Ustadz Purwanto",
    family: "Groom",
    association: "Guru Tahsin",
  },
  {
    id: "CPP021",
    name: "Agam",
    family: "Groom",
    association: "Teman PDAM",
  },
  {
    id: "CPP022",
    name: "Faisal",
    family: "Groom",
    association: "Teman PDAM",
  },
  {
    id: "CPP023",
    name: "Mang Ridwan",
    family: "Groom",
    association: "Teman PDAM",
  },
  {
    id: "CPP024",
    name: "Masjid Khidmatus Sunnah",
    family: "Groom",
    association: "",
  },
  {
    id: "CPP025",
    name: "Pengabdian El Azzam La Tansa",
    family: "Groom",
    association: "",
  },
  {
    id: "CPP026",
    name: "Keluarga Besar H. Sukra",
    family: "Groom",
    association: "",
  },
  {
    id: "CPP027",
    name: "Keluarga Besar H. Sukra",
    family: "Groom",
    association: "",
  },
  {
    id: "CPP028",
    name: "Keluarga Besar Hj Gancang",
    family: "Groom",
    association: "",
  },
  {
    id: "CPP029",
    name: "Keluarga Besar H. Syukriyah",
    family: "Groom",
    association: "",
  },
  {
    id: "CPW001",
    name: "Keluarga Besar Achmad Roedja'i",
    family: "Bride",
    association: "",
  },
  {
    id: "CPW002",
    name: "Keluarga Besar Hikmat Setiawan",
    family: "Bride",
    association: "",
  },
  {
    id: "CPW003",
    name: "Yayasan Pendidikan Islam Imam Ahmad bin Hanbal",
    family: "Bride",
    association: "",
  },
  {
    id: "CPW004",
    name: "Bulan Bintang Islamic School",
    family: "Bride",
    association: "",
  },
  {
    id: "CPW005",
    name: "Mu'allimat Rattil Ayatihi",
    family: "Bride",
    association: "",
  },
  {
    id: "CPW006",
    name: "Mu'allimat Daarunnisaa",
    family: "Bride",
    association: "",
  },
  {
    id: "CPW007",
    name: "Mu'allimat Nurul Ilmi Lil Athfal",
    family: "Bride",
    association: "",
  },
  {
    id: "CPW008",
    name: "Rumah Cinta Quran",
    family: "Bride",
    association: "",
  },
  {
    id: "CPW009",
    name: "Thalibat Tahsin Shahabah Mengaji",
    family: "Bride",
    association: "",
  },
  {
    id: "CPW010",
    name: "Tim Janaiz Akhawat Masjid Nurul Iman Blok M Square",
    family: "Bride",
    association: "",
  },
  {
    id: "CPW011",
    name: "Ambarita Mumpuni",
    family: "Bride",
    association: "Teman SMP",
  },
  {
    id: "CPW012",
    name: "Meiliana Indri Sagita",
    family: "Bride",
    association: "Teman SMP",
  },
  {
    id: "CPW013",
    name: "Dini Hanifah",
    family: "Bride",
    association:
      "Teman Ma'had dan kuliah. Kemungkinan hadir dengan suami dan anaknya (bayi).",
  },
  {
    id: "CPW014",
    name: "Kinta Nilaya Aprira",
    family: "Bride",
    association:
      "Teman SMP. Kemungkinan besar tidak hadir karena tinggal di Bengkulu.",
  },
  {
    id: "CPW015",
    name: "Megawati",
    family: "Bride",
    association: "Teman SMP. Kemungkinan hadir dengan suami dan anak (balita).",
  },
  {
    id: "CPW016",
    name: "Teh Virna Nur'afianty Dewi",
    family: "Bride",
    association:
      "Teman kajian di Bandung. Kemungkinan hadir dengan suami dan anaknya (bayi).",
  },
  {
    id: "CPW017",
    name: "Teh Shofiyah Asmanadyah",
    family: "Bride",
    association:
      "Teman kajian di Bandung. Kemungkinan besar tidak hadir karena ada bayi.",
  },
  {
    id: "CPW018",
    name: "Rizqiah",
    family: "Bride",
    association:
      "Teman kajian di Bandung. Sudah dikonfirmasi tidak hadir karena memiliki bayi.",
  },
  {
    id: "CPW019",
    name: "Yasfika Ely Nur Afifah",
    family: "Bride",
    association: "Teman Ma'had dan kuliah.",
  },
  {
    id: "CPW020",
    name: "Erika Khairunnisa",
    family: "Bride",
    association: "Teman Ma'had dan kuliah. Kemungkinan besar tidak hadir.",
  },
  {
    id: "CPW021",
    name: "Rizka Amelia",
    family: "Bride",
    association:
      "Teman Ma'had dan kuliah. Kemungkinan besar tidak hadir karena tinggal di Medan.",
  },
  {
    id: "CPW022",
    name: "Teh Asy-Syifa Rizqiawati Casmat",
    family: "Bride",
    association: "Kemungkinan hadir dengan suami.",
  },
  {
    id: "CPW023",
    name: "Ummu Santy Purnamasari",
    family: "Bride",
    association: "Murid tahsin privat",
  },
  {
    id: "CPW024",
    name: "Ummu dr. Desvita Rosana, Sp.An",
    family: "Bride",
    association: "Murid tahsin privat",
  },
  {
    id: "CPW025",
    name: "Ummu Tuti Alawiyah",
    family: "Bride",
    association: "Murid tahsin privat",
  },
  {
    id: "CPW026",
    name: "Bu Enalita",
    family: "Bride",
    association: "Murid tahsin privat",
  },
  {
    id: "CPW027",
    name: "Aida Rahmah Nuralimah",
    family: "Bride",
    association: "Kemungkinan hadir dengan suami.",
  },
  {
    id: "CPW028",
    name: "Nopiya",
    family: "Bride",
    association: "",
  },
  {
    id: "CPW029",
    name: "Bu Tia Ummu Manda",
    family: "Bride",
    association:
      "Orang tua murid tahfidz privat. Ragu hadir atau tidak. Kalau hadir kemungkinan besar dengan keluarga.",
  },
  {
    id: "CPW030",
    name: "Bunda Ratih Ummu Fatih",
    family: "Bride",
    association: "Orang tua murid privat",
  },
];
